/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.custom.query.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.liferay.sample.custom.query.model.Custom;
import com.liferay.sample.custom.query.model.CustomModel;
import com.liferay.sample.custom.query.model.CustomSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Custom service. Represents a row in the &quot;SAMPLE_Custom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CustomModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CustomImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CustomImpl
 * @see Custom
 * @see CustomModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CustomModelImpl extends BaseModelImpl<Custom>
	implements CustomModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a custom model instance should use the {@link Custom} interface instead.
	 */
	public static final String TABLE_NAME = "SAMPLE_Custom";
	public static final Object[][] TABLE_COLUMNS = {
			{ "customId", Types.BIGINT },
			{ "customName", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("customId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("customName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table SAMPLE_Custom (customId LONG not null primary key,customName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table SAMPLE_Custom";
	public static final String ORDER_BY_JPQL = " ORDER BY custom.customId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SAMPLE_Custom.customId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.example.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.sample.custom.query.model.Custom"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.example.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.sample.custom.query.model.Custom"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Custom toModel(CustomSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Custom model = new CustomImpl();

		model.setCustomId(soapModel.getCustomId());
		model.setCustomName(soapModel.getCustomName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Custom> toModels(CustomSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Custom> models = new ArrayList<Custom>(soapModels.length);

		for (CustomSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.example.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.sample.custom.query.model.Custom"));

	public CustomModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _customId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCustomId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _customId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Custom.class;
	}

	@Override
	public String getModelClassName() {
		return Custom.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("customId", getCustomId());
		attributes.put("customName", getCustomName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long customId = (Long)attributes.get("customId");

		if (customId != null) {
			setCustomId(customId);
		}

		String customName = (String)attributes.get("customName");

		if (customName != null) {
			setCustomName(customName);
		}
	}

	@JSON
	@Override
	public long getCustomId() {
		return _customId;
	}

	@Override
	public void setCustomId(long customId) {
		_customId = customId;
	}

	@JSON
	@Override
	public String getCustomName() {
		if (_customName == null) {
			return "";
		}
		else {
			return _customName;
		}
	}

	@Override
	public void setCustomName(String customName) {
		_customName = customName;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Custom.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Custom toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Custom)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CustomImpl customImpl = new CustomImpl();

		customImpl.setCustomId(getCustomId());
		customImpl.setCustomName(getCustomName());

		customImpl.resetOriginalValues();

		return customImpl;
	}

	@Override
	public int compareTo(Custom custom) {
		long primaryKey = custom.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Custom)) {
			return false;
		}

		Custom custom = (Custom)obj;

		long primaryKey = custom.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Custom> toCacheModel() {
		CustomCacheModel customCacheModel = new CustomCacheModel();

		customCacheModel.customId = getCustomId();

		customCacheModel.customName = getCustomName();

		String customName = customCacheModel.customName;

		if ((customName != null) && (customName.length() == 0)) {
			customCacheModel.customName = null;
		}

		return customCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{customId=");
		sb.append(getCustomId());
		sb.append(", customName=");
		sb.append(getCustomName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.liferay.sample.custom.query.model.Custom");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>customId</column-name><column-value><![CDATA[");
		sb.append(getCustomId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>customName</column-name><column-value><![CDATA[");
		sb.append(getCustomName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Custom.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Custom.class, ModelWrapper.class
		};
	private long _customId;
	private String _customName;
	private Custom _escapedModel;
}