/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.sample.custom.query.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Custom service. Represents a row in the &quot;SAMPLE_Custom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.sample.custom.query.model.impl.CustomModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.sample.custom.query.model.impl.CustomImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Custom
 * @see com.liferay.sample.custom.query.model.impl.CustomImpl
 * @see com.liferay.sample.custom.query.model.impl.CustomModelImpl
 * @generated
 */
@ProviderType
public interface CustomModel extends BaseModel<Custom> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a custom model instance should use the {@link Custom} interface instead.
	 */

	/**
	 * Returns the primary key of this custom.
	 *
	 * @return the primary key of this custom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this custom.
	 *
	 * @param primaryKey the primary key of this custom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the custom ID of this custom.
	 *
	 * @return the custom ID of this custom
	 */
	public long getCustomId();

	/**
	 * Sets the custom ID of this custom.
	 *
	 * @param customId the custom ID of this custom
	 */
	public void setCustomId(long customId);

	/**
	 * Returns the custom name of this custom.
	 *
	 * @return the custom name of this custom
	 */
	@AutoEscape
	public String getCustomName();

	/**
	 * Sets the custom name of this custom.
	 *
	 * @param customName the custom name of this custom
	 */
	public void setCustomName(String customName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Custom custom);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Custom> toCacheModel();

	@Override
	public Custom toEscapedModel();

	@Override
	public Custom toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}